extends: eslint:recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - 'prettier'
  - 'jest'
env:
  jest/globals: true
  es2021: true
  node: true
rules:
  prettier/prettier:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
